package agentmanager

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"

	"github.com/aoagents/agent-orchestrator/backend/internal/domain"
	"github.com/aoagents/agent-orchestrator/backend/internal/httpd/apierr"
	"github.com/aoagents/agent-orchestrator/backend/internal/ports"
)

// RegistryActionInput is native authoring output and retry identity, never
// caller-supplied authority. Registry identity is generated by this service.
type RegistryActionInput struct {
	SourceGeneration string                            `json:"sourceGeneration"`
	IdempotencyKey   string                            `json:"idempotencyKey"`
	Action           domain.AgentManagerRegistryAction `json:"action"`
}

// RegistryActionReceipt retains the sealed authoring outcome and its target.
type RegistryActionReceipt struct {
	Receipt domain.AgentManagerRegistryReceipt `json:"receipt"`
	Created bool                               `json:"created"`
}

type nativeRegistryStore interface {
	ports.AgentManagerRegistryStore
	GetSession(context.Context, domain.SessionID) (domain.SessionRecord, bool, error)
}

func (m *Manager) registryStore() (nativeRegistryStore, error) {
	store, ok := m.store.(nativeRegistryStore)
	if !ok {
		return nil, apierr.NotImplemented("AGENT_MANAGER_REGISTRY_UNAVAILABLE", "Manager registry authoring persistence is unavailable")
	}
	return store, nil
}

func mapRegistryError(err error) error {
	switch {
	case err == nil:
		return nil
	case errors.Is(err, ports.ErrAgentManagerNotFound):
		return apierr.NotFound("AGENT_MANAGER_REQUEST_NOT_FOUND", "Manager request was not found in this project")
	case errors.Is(err, ports.ErrAgentManagerConflict):
		return apierr.Conflict("AGENT_MANAGER_REGISTRY_CONFLICT", "Registry authoring changed, a retry differs, or a request/policy quota was reached; inspect retained receipts", nil)
	case errors.Is(err, ports.ErrAgentManagerFenced):
		return apierr.Conflict("AGENT_MANAGER_WORK_FENCED", "The authoring source is not the current live Manager generation or its sealed input", nil)
	case errors.Is(err, ports.ErrAgentManagerForbidden):
		return apierr.Forbidden("AGENT_MANAGER_REGISTRY_FORBIDDEN", "Governance policy, ownership or conversation classification refuses this authoring action")
	case errors.Is(err, ports.ErrAgentManagerInvalid):
		return apierr.Invalid("INVALID_AGENT_MANAGER_REGISTRY", err.Error(), nil)
	default:
		return err
	}
}

// AuthorRegistryAction derives native attribution from session facts and lets
// the store transaction recheck delivery fencing, policy quotas and
// classification. Registry entry identity is minted here, never claimed by
// native output.
func (m *Manager) AuthorRegistryAction(ctx context.Context, sessionID domain.SessionID, requestID string, input RegistryActionInput) (RegistryActionReceipt, error) {
	var receipt RegistryActionReceipt
	if err := validateProject(domain.ProjectID(input.SourceGeneration)); err != nil {
		return receipt, apierr.Invalid("INVALID_MANAGER_GENERATION", "A bounded native sourceGeneration is required", nil)
	}
	createdEntryID := ""
	if input.Action.Action == "create" {
		createdEntryID = uuid.NewString()
	}
	submission := domain.AgentManagerRegistrySubmission{ID: uuid.NewString(), CreatedEntryID: createdEntryID, ProjectID: "pending-session-lookup", RequestID: requestID, SessionID: sessionID, SourceOwner: domain.SessionControllerOwner{}, IdempotencyKey: input.IdempotencyKey, Action: input.Action, Now: time.Now().UTC()}
	if err := submission.Validate(); err != nil {
		return receipt, apierr.Invalid("INVALID_AGENT_MANAGER_REGISTRY", err.Error(), nil)
	}
	store, err := m.registryStore()
	if err != nil {
		return receipt, err
	}
	rec, found, err := store.GetSession(ctx, sessionID)
	if err != nil {
		return receipt, err
	}
	if !found {
		return receipt, mapRegistryError(ports.ErrAgentManagerNotFound)
	}
	owner := rec.ControllerOwner()
	generation := owner.RuntimeLaunchID
	if owner.Mode == domain.SessionModeChat {
		generation = owner.ControllerGeneration
	}
	if rec.Kind != domain.KindAgentManager || rec.ProjectID == "" || rec.IsTerminated || generation != input.SourceGeneration {
		return receipt, apierr.Conflict("AGENT_MANAGER_OWNER_CHANGED", "The authoring source is not the current live Manager generation", nil)
	}
	submission.ProjectID, submission.SourceOwner = rec.ProjectID, owner
	receipt.Receipt, receipt.Created, err = store.ApplyAgentManagerRegistryAction(ctx, submission)
	return receipt, mapRegistryError(err)
}

// RegistryReceipts pages a request's retained authoring receipts (limit 1-100).
func (m *Manager) RegistryReceipts(ctx context.Context, project domain.ProjectID, requestID, afterID string, limit int) ([]domain.AgentManagerRegistryReceipt, error) {
	if err := validateProject(project); err != nil {
		return nil, err
	}
	if _, err := m.Request(ctx, project, requestID); err != nil {
		return nil, err
	}
	store, err := m.registryStore()
	if err != nil {
		return nil, err
	}
	if limit < 1 || limit > 100 {
		return nil, apierr.Invalid("INVALID_AGENT_MANAGER_PAGE", "Registry receipt limit must be between 1 and 100", nil)
	}
	if afterID != "" {
		if err := validateProject(domain.ProjectID(afterID)); err != nil {
			return nil, apierr.Invalid("INVALID_AGENT_MANAGER_PAGE", "afterId must be nonempty, bounded and contain no control characters", nil)
		}
	}
	items, err := store.ListAgentManagerRegistryReceipts(ctx, project, requestID, afterID, limit)
	return items, mapRegistryError(err)
}

// RegistryReceipt reads one exact retained authoring receipt.
func (m *Manager) RegistryReceipt(ctx context.Context, project domain.ProjectID, requestID, receiptID string) (domain.AgentManagerRegistryReceipt, error) {
	if err := validateProject(domain.ProjectID(receiptID)); err != nil {
		return domain.AgentManagerRegistryReceipt{}, apierr.Invalid("INVALID_AGENT_MANAGER_REGISTRY", "A bounded receipt ID is required", nil)
	}
	if _, err := m.Request(ctx, project, requestID); err != nil {
		return domain.AgentManagerRegistryReceipt{}, err
	}
	store, err := m.registryStore()
	if err != nil {
		return domain.AgentManagerRegistryReceipt{}, err
	}
	receipt, err := store.GetAgentManagerRegistryReceipt(ctx, project, requestID, receiptID)
	return receipt, mapRegistryError(err)
}
