#!/bin/bash

echo "🚀 Quick Start Guide - Cloud Agent Credentials Testing"
echo "======================================================"
echo ""
echo "✅ PostgreSQL is already running!"
echo "   Container: ao-postgres"
echo "   Port: 5432"
echo "   User: aoadmin"
echo "   Password: aopass"
echo "   Database: cloud"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 NEXT STEPS (open 2 more terminals):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔵 TERMINAL 2: Start Cloud Backend"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cd /Users/nikhilachale/Desktop/agent-orchestrator/cloud"
echo ""
echo "  export POSTGRES_URL='postgres://aoadmin:aopass@localhost:5432/cloud'"
echo ""
echo "  go run ./cmd/server -addr=0.0.0.0:9090"
echo ""
echo "  ✅ You should see: 'Listening on http://0.0.0.0:9090'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🟣 TERMINAL 3: Start Frontend"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cd /Users/nikhilachale/Desktop/agent-orchestrator/frontend"
echo ""
echo "  npm install  # First time only"
echo ""
echo "  npm start"
echo ""
echo "  ✅ You should see: 'Local: http://localhost:3000'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 TESTING CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Open http://localhost:3000"
echo ""
echo "2️⃣  Create a Cloud Project:"
echo "    Dashboard → New Project → Cloud"
echo "    Name: 'Local Test'"
echo "    Repo: 'https://github.com/user/test'"
echo "    Branch: 'main'"
echo ""
echo "3️⃣  Create a Task (NO CREDENTIALS):"
echo "    Open Project → Create Task"
echo "    Agent Dropdown - What do you see?"
echo "    ❌ Should show ALL 3 agents but ALL DISABLED"
echo "    ❌ Each should show 'Needs auth' hint"
echo ""
echo "4️⃣  Add a Credential:"
echo "    Settings → Cloud → Add Credential"
echo "    Agent: Claude Code"
echo "    Type: Setup token"
echo "    Token: (any test value, will fail validation but that's ok)"
echo ""
echo "5️⃣  Refresh and Create Task Again:"
echo "    Go back to project → Create Task"
echo "    ✅ Claude Code should now be ENABLED"
echo "    ❌ Codex and Cursor still disabled"
echo ""
echo "6️⃣  Test the Endpoint:"
echo "    curl http://localhost:9090/api/cloud/v1/me"
echo "    (Should return user info if authenticated)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Full Guide:"
echo "   cat /Users/nikhilachale/Desktop/agent-orchestrator/LOCAL_TESTING.md"
echo ""
echo "🛑 Stop all services:"
echo "   docker-compose -f docker-compose.dev.yml down"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
